apiVersion: batch/v1
kind: Job
metadata:
  generateName: free-deployment-
spec:
  template:
    spec:
      containers:
      - name: free
        env:
        - name: TYPE
          value: "ff"
        - name: DATASET
          value: "mnist"  
        command: ["docker", "container", "run", "frellwan/cs498:mp3"]
      restartPolicy: Never
  backoffLimit: 4


  