admin/resource/quota-mem-cpu-pod.yaml 

apiVersion: v1
kind: Pod
metadata:
  name: quota-mem-cpu-demo
spec:
  containers:
  - name: quota-mem-cpu-demo-ctr
    image: nginx
    resources:
      limits:
        cpu: "2" 
      requests:
        cpu: "0.9"
      
