apiVersion: batch/v1
kind: Job
metadata:
  generateName: free-deployment-
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["docker",  "container", "run", "frellwan/cs498:mp3"]
      restartPolicy: Never
  backoffLimit: 4

